font:
  normal:
    family: Hasklig
    style: Regular
  bold:
    family: Hasklig
    style: Bold
  italic:
    family: Hasklig
    style: Italic
# Colors (Monokai Dark)
colors:
  # Default colors
  primary:
    background: '#212121'
    foreground: '#F8F8F2'

  # Normal colors
  normal:
   black:   '#272822'
   red:     '#F92672'
   green:   '#A6E22E'
   yellow:  '#F4BF75'
   blue:    '#66D9EF'
   magenta: '#AE81FF'
   cyan:    '#A1EFE4'
   white:   '#F8F8F2'

  # Bright colors
  bright:
   black:   '#75715E'
   red:     '#F92672'
   green:   '#A6E22E'
   yellow:  '#F4BF75'
   blue:    '#66D9EF'
   magenta: '#AE81FF'
   cyan:    '#A1EFE4'
   white:   '#F9F8F5'
