[window]
width = 960
height = 620
scale_factor = 1.0
opacity = 1.0

[terminal]
default_cols = 104
default_rows = 32
scrollback = 2000

[env]
TERM = "xterm-256color"

[font]
family = "Fira Code"
style = "Regular"
size = 18

[cursor.model]
path = "CairoSpinyMouse.obj"
scale_factor = 6.0
brightness = 0.5
x_offset = 0.5
plane_offset = 18.0
visible = false

[cursor.animation]
spin_speed = 1.4
bob_speed = 2.2
bob_amplitude = 0.08

[bindings]
keys = [
  { key = "C", with = "Control | alt", action = "Copy" },
  { key = "V", with = "Control | alt", action = "Paste" },
  { key = "PageUp", with = "alt", action = "ScrollPageUp" },
  { key = "PageDown", with = "alt", action = "ScrollPageDown" },
  { key = "Up", with = "alt", action = "ScrollUp" },
  { key = "Down", with = "alt", action = "ScrollDown" },
  { key = "Equal", with = "Control", action = "IncreaseFontSize" },
  { key = "Minus", with = "Control", action = "DecreaseFontSize" },
  { key = "Digit0", with = "Control | alt", action = "ResetFontSize" },
  { key = "Enter", with = "Control | alt", action = "Toggle3DMode" },
  { key = "M", with = "Control | alt", action = "ToggleMobiusMode" },
  { key = "Up", with = "Control | alt", action = "IncreaseWarp" },
  { key = "Down", with = "Control | alt", action = "DecreaseWarp" },
]

[theme]
foreground = "#d8dee9"
background = "#2e3440"
cursor = "#d8dee9"

[theme.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[theme.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"
